substitutions:
  _IMAGE_NAME: mieszkaniownik-frontend
  _ARTIFACT_REGISTRY: europe-west3-docker.pkg.dev
  _REPOSITORY: mieszkaniownik-repo

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "--tag=${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
      - "--tag=${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest"
      - "--build-arg=VITE_API_BASE_URL=https://api.mieszkaniownik.wsparcie.dev"
      - "--build-arg=VITE_GOOGLE_MAPS_API_KEY=AIzaSyCZNUevcLWeWrJ5dXe9IIHxWNu4XrWmGFU"
      - "--cache-from=${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - "push"
      - "${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      - "push"
      - "${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest"

images:
  - "${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
  - "${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest"

timeout: "1200s"
