apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    environment: development

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cache-config
  namespace: production
data:
  cache-control-max-age: "31536000"
  cache-control-html: "no-cache, no-store, must-revalidate"
  cdn-enabled: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cache-config
  namespace: development
data:
  cache-control-max-age: "3600"
  cache-control-html: "no-cache"
  cdn-enabled: "false"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: production
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mieszkaniownik-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mieszkaniownik-frontend
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: production
        - podSelector:
            matchLabels:
              app: mieszkaniownik-backend
      ports:
        - protocol: TCP
          port: 5001
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mieszkaniownik-frontend-pdb
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mieszkaniownik-frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mieszkaniownik-frontend-pdb
  namespace: development
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mieszkaniownik-frontend

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-quota
  namespace: development
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
